import Category from '@/components/category'
import style from '@/pages/shopping/index.module.css'
import Head from 'next/head'
import Link from 'next/link'



function Shop({ products }) {


    return (
        <>

            <Head>
                <title>shopping</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <section>
                <Category />
            </section>


            <section>
                <div className='d-md-flex flex-row justify-content-center main_product_category'>
                    {
                        products.map(item => {
                            return (

                                <div key={item.id} className='card product_category'>
                                    <Link href={`/shopping/${item.id}`}>
                                        <img src={item.image} className='card-img-top' />
                                    </Link>
                                    <div className='card-body'>
                                        <h3>{item.title}</h3>
                                        <h4>price: ${item.price}</h4>
                                        <span>{item.category}</span>
                                        <p>{item.description}</p>
                                    </div>
                                </div>

                            )
                        })
                    }
                </div>
            </section>
        </>
    )
}




export async function getStaticProps() {
    const res = await fetch('https://fakestoreapi.com/products')
    const data = await res.json()

    return {
        props: {
            products: data,
        }
    }
}

export default Shop;